
export const ATTRIBUTE_TYPE = {
    BASIC: 0,
    KEY: 1,
    SALE: 2
}
ATTRIBUTE_TYPE[ATTRIBUTE_TYPE.BASIC] = "基础属性";
ATTRIBUTE_TYPE[ATTRIBUTE_TYPE.KEY] = "关键属性";
ATTRIBUTE_TYPE[ATTRIBUTE_TYPE.SALE] = "销售属性";